packages:
  - apps/browser/*/*
  - apps/server/*/*

  - packages/browser/*/*
  - packages/server/*/*
  - packages/workspace/*/*

  - '!**/__docs/**'
  - '!**/__test__/**'

catalog:
  '@types/node': ^22.7.5
  turbo: ^2.1.3
  typescript: ^5.6.3
  vite: ^6.0.1