packages:
  - 'packages/framework/**'
  - 'packages/tools/**'
  - '!**/__test__/**'

catalog:
  '@biomejs/biome': 1.9.3
  '@types/node': 22.7.5
  '@tsconfig/node22': 22.0.0
  '@tsconfig/strictest': 2.0.5
  tsup: 8.3.0
  vitest: 2.1.2
  del-cli: 6.0.0
  typescript: 5.6.3
  turbo: 2.1.3